import type { Metadata } from "next"
import { Geist, Geist_Mono, Inter } from "next/font/google"
import "./globals.css"
import type {ReactNode} from "react"

const fontSans = Inter({ subsets:['latin'], variable:'--font-sans' })

const geistMono = Geist_Mono({ variable: "--font-mono", subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Marius Ahsmus",
    description: "Generated by create next app"
}

export default function RootLayout({children}: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en" className={`${geistMono.variable} ${fontSans.variable}`}>
            <body className={"antialiased"}>
                {children}
            </body>
        </html>
    )
}
